name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd packages/protocols && npm install
    - run: cd packages/sdk && npm install
    - run: cd services/client && npm install
    - run: npm start
    - run: cd services/server && npm install
    #- run: cd services/server && npm run build --if-present
    - run: npm start
    - run: npm test
      env:
        CI: true
    - name: Docker Publish
      uses: manusa/actions-publish-docker@v1.0.1
      with:
        # Name of the Docker image
        name: erebus
        # Tag for the Docker image
        #tag: # optional
        # Script body to compute tag name for the Docker image, has context as the main function argument
        #tag script: # optional
        # Username for Docker registry
        username: vivisima
        # Password for Docker registry
        password: nigiBox02
        # Registry URL
        #registry: # optional
        # Don't skip pull requests
        #include pull requests: # optional
